worker_processes auto;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    upstream flask_backends {
        server app-01:8080 ;
        server app-02:8080 ;
        
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flask_backends;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Enable non-idempotent HTTP methods retry if needed and catch connection resets/errors
            proxy_next_upstream error timeout invalid_header http_502 http_503 http_504 non_idempotent;
            proxy_next_upstream_tries 3;
            proxy_next_upstream_timeout 5s;
            proxy_connect_timeout 1s;
            proxy_read_timeout 2s;
        }
    }
}